[package]
name = "psxtest"
version = "0.1.0"
authors = ["Merwan <achibet.merwan@gmail.com>"]
edition = "2018"

[dependencies]
psx = { path = "../psx" }
imgui = "0.3.0"
glium = { version = "0.26", default-features = true }
imgui-glium-renderer = "0.3.0"
imgui-winit-support = "0.3.0"
