[package]
name = "psx"
version = "0.1.0"
authors = ["Merwan <achibet.merwan@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.104"
serde_json = "1.0.48"
bitfield = "0.13.2"
